### ISSUE TITLE
Виртуальные функции

### ISSUE THREAD

**Issue by DanAnastasyev** [andreyzharkov/plc#2]
1. Неплохо бы иметь доступ к полям классов из его методов
2. Подумай, как обойтись без ручной очистки vfuncs в main. Сейчас такой код падает после твоей чистки: `VIRTUAL_CALL((&derived), OnlyDerived);`

**Comment by reyzharkov** [comment]
1. Вообще этого в явном виде не требовалось в задании 😄 . Понятно что надо как-то VA_ARGS использовать в лямбде или умудриться прокинуть this (которого нет при DECLARE_METHOD т.к. он объявляется вне объявления класса), но как именно честно сейчас не хочется разбираться. Если бы еще ревью было проведено не 3 дня назад в разгар зачетной недели я бы посмотрел, а так извиняюсь.
2. Это да, поправил.
